{
 "title": "Prometheus BenchMark",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "data ingestion rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(vm_promscrape_scraped_samples_sum{job=\"vmagent\"})) by (remote_storage_name)"
    }
   ]
  },
  {
   "title": "99th percentile for the duration to execute queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "max(vmalert_iteration_duration_seconds{quantile=\"0.99\",job=\"vmalert\"}) by (remote_storage_name)"
    }
   ]
  },
  {
   "title": "99th percentile for the duration to push the collected data to the configured   remote storage systems",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum(increase(vmagent_remotewrite_duration_seconds_bucket{job=\"vmagent\"}[5m])) by (vmrange,remote_storage_name)\n)"
    }
   ]
  },
  {
   "title": "The number of dropped data packets when sending them to the configured remote storage.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(vmagent_remotewrite_packets_dropped_total{job=\"vmagent\"})) by (remote_storage_name)"
    }
   ]
  },
  {
   "title": "The number of retries when sending data to remote storage.",
   "type": "timeseries",
   "description": "If the value is bigger than zero,\n  then this is a sign that the remote storage cannot handle the workload.\n  It is recommended inspecting remote storage logs and vmagent logs in this case.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(vmagent_remotewrite_retries_count_total{job=\"vmagent\"})) by (remote_storage_name)"
    }
   ]
  },
  {
   "title": "The amounts of pending data at vmagent side, which isn't sent to remote storage yet.",
   "type": "timeseries",
   "description": "If the graph grows, then the remote storage cannot keep up with the given data ingestion rate.\n  Sometimes increasing the `writeConcurrency` at [chart/values.yaml](chart/values.yaml)\n  may help if there is a high network latency between vmagent at prometheus-benchmark\n  and the remote storage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(vm_persistentqueue_bytes_pending{job=\"vmagent\"}) by (remote_storage_name)"
    }
   ]
  },
  {
   "title": "The number of errors when executing queries",
   "type": "timeseries",
   "description": "If the value is bigger than zero, then the remote storage cannot handle the query workload.\n  It is recommended inspection remote storage logs and vmalert logs in this case.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(vmalert_execution_errors_total{job=\"vmalert\"})) by (remote_storage_name)"
    }
   ]
  }
 ]
}